version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
